name: GitHub CI
on: 
  push:
    branches: [master, main]





jobs:
  linux64_build_x86_64:
    name: Linux x86_64 Build
    if: contains(github.event.head_commit.message, 'build-linux')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add commit id into version
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: subconverter_linux64
        path: subconverter/
    - name: Package Release
      run: tar czf subconverter_linux64.tar.gz subconverter
    - name: Draft Release
      uses: softprops/action-gh-release@v2
      with:
        files: subconverter_linux64.tar.gz
        draft: true



  